### ISSUE TITLE
port for protobuf and grpc libraries

### ISSUE THREAD

**Issue by trimpim** [genodelabs/genode-world#190]

**Comment by trimpim** [comment]
Some changes are needed to protobuf to enable integration with the gRPC library.

**Comment by trimpim** [comment]
@chelmuth and @nfeske Except form some missing symbols in `stdcxx` that are in staging the libraries can now be used.

**Comment by nfeske** [comment]
@trimpim: Wow! That is impressive work. Thanks for the comprehensive commit. I merged it to master just now.

**Comment by chelmuth** [comment]
@trimpim I fixed the hash of protobuf_grpc and then gave `prepare_port` a spin for testing. IMO the following two things needs consideration.

1. The protobuf_grpc port consumes 749M disk space, which is pretty much for *just an RPC framework*. Do you see any chance to reduce this, e.g., by using an archive download instead of `git clone`?
2. The run of `prepare_port` failed with
```
> ./tool/ports/prepare_port protobuf_grpc
protobuf_grpc  download https://github.com/protocolbuffers/protobuf.git
protobuf_grpc  git Cloning into 'src/lib/protobuf'...
protobuf_grpc  update src/lib/protobuf
protobuf_grpc  download https://github.com/grpc/grpc.git
protobuf_grpc  git Cloning into 'src/lib/grpc'...
protobuf_grpc  update src/lib/grpc
protobuf_grpc  download https://github.com/grpc/grpc.git
protobuf_grpc  git Cloning into 'src/lib/grpc-host'...
protobuf_grpc  update src/lib/grpc-host
protobuf_grpc  apply src/lib/protobuf/patches/01-mutex.patch
protobuf_grpc  apply src/lib/protobuf/patches/02-run_once.patch
protobuf_grpc  apply src/lib/protobuf/patches/03-thread.patch
protobuf_grpc  apply src/lib/grpc/patches/01_mutex.patch
protobuf_grpc  apply src/lib/grpc/patches/02_generated_includes.patch
protobuf_grpc  apply src/lib/grpc/patches/03_if_nametoindex.patch
protobuf_grpc  apply src/lib/grpc/patches/04_socket_stuff.patch
protobuf_grpc  apply src/lib/grpc/patches/05_example.patch
protobuf_grpc  apply src/lib/grpc/patches/06_if_indextoname.patch
protobuf_grpc  apply src/lib/grpc/patches/07_send_recv.patch
Error: Could not find patch src/lib/grpc/patches/07_send_recv.patch
.../tool/ports/mk/install.mk:124: recipe for target 'phony/patches/src/lib/grpc/patches/07_send_recv.patch' failed
make[2]: *** [phony/patches/src/lib/grpc/patches/07_send_recv.patch] Error 1
.../tool/ports/mk/prepare_single_port.mk:38: recipe for target '_install_in_port_dir' failed
make[1]: *** [_install_in_port_dir] Error 2
tool/ports/prepare_port:47: recipe for target 'protobuf_grpc' failed
make: *** [protobuf_grpc] Error 2
```

**Comment by nfeske** [comment]
Maybe a "shallow" git clone (specifying a `--depth` argument) could help?

**Comment by chelmuth** [comment]
With `git clone --depth=1 https://github.com/grpc/grpc.git test` I still get 115M (with *only* 20M in *test/.git*).

**Comment by trimpim** [comment]
@chelmuth  and @nfeske  I will have a look at the issues. But it may take some days.

**Comment by chelmuth** [comment]
I removed the commits from master until a proper fix is provided. With the commits our nightly stalls about 40 min trying to get the port in shape, which always fails.

**Comment by chelmuth** [comment]
I was not able to successfully execute *tool/tool_chain_protobuf* because of link errors on Ubuntu 16.04.6 LTS. Does it work on 18.04/bionic?

**Comment by ssumpf** [comment]
@chelmuth: I had the same issue, one needs a host protobuf library which is close to the one for Genode (3.9.1), since protobuf needs protobuf to build protobuf - the usual bootstrap game these days ;)

**Comment by trimpim** [comment]
I had tested it on Ubuntu 18.04 and arch Linux, where it worked.

If I find some time during the holiday season I will add a check for the protobuf version of the host.

**Comment by chelmuth** [comment]
> one needs a host protobuf library which is close to the one for Genode (3.9.1), since protobuf needs protobuf to build protobuf - the usual bootstrap game these days ;)

Yeah, that's expected, but I also expect the compiler to bootstrap itself like others do. Especially in this case this should be a no-brainer as it isn't a C compiler but *just an™* RPC generator.

**Comment by chelmuth** [comment]
With the information from https://askubuntu.com/a/1072684 and VERSION=3.9.1, I was able to build *protoc* for Ubuntu 16.04. Then I was also able to run *tool_chain_protobuf* successfully and now have two 3.9.1 protoc installations but may also succeed to build the grpc Genode packages.

Nevertheless, I'm still wondering why building from source works for the upstream archive but not with tool_chain_protobuf...

**Comment by ssumpf** [comment]
@chelmuth: As far as I can tell this has something to do with the generated header files, they have a version check in there. Maybe they can be generated in a different way.

**Comment by trimpim** [comment]
@chelmuth: While testing I have found out, that if no `protoc` is installed from the distribution (Ubuntu 18.04) building succeeds, but if `protoc` (default vewrsion) is installed building `gRPC` fails. This is  the case when I instruct `cmake` to use `protobuf` as package as it is currently (`protobuf` is built and installed before `gRPC`) (`gRPC` tries to find the 'correct' `protoc` to use).

I then tried to instruct `cmake` to use `protobuf` as module, so that it directly uses the source that is downloaded in to the `third_party` directory. I was able to build and install `gRPC` this way, but when I tried to build the test applications I got an error message about mismatching `protoc` versions.

I am still trying to find a good solution for this. IMHO the tools for `protobuf` and `gRPC` should be self contained and not interfere with `protoc` that is eventually installed from the distro.

**Comment by trimpim** [comment]
@chelmuth my latest changes allow me to build the toolchain for `protobuf` and 'gRPC` independent of the version of `protoc` installed by the distribution. I tested it on my Ubuntu 18.04 and my ARCH workstation at home.

**Comment by chelmuth** [comment]
It will take some days before I can test your patch.

**Comment by trimpim** [comment]
@chelmuth sorry for the bump, did you already have time to look in to this?

**Comment by chelmuth** [comment]
Sorry that it took so long and thanks for the nudge. I tested your commits with `tool_chain_protobuf` and `run/grpc` and have no objections. Also, I updated *master* with your commits.

**Comment by trimpim** [comment]
@chelmuth many thanks for the information.
